language: php

php:
  - 5.6
  - 7.0
  - 7.1

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    
before_install:
  - composer config --global github-oauth.github.com $GITHUB_TOKEN
  
install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:^1.3.1"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction

script: 
  - vendor/bin/codecept build
  - vendor/bin/codecept run
